runtime: python 3.9
entrypoint: gunicorn -b :$PORT main:app

instance_class: F2

env_variables:
  GOOGLE_CLOUD_PROJECT: "My app"
  ENV: "production"

handlers:
  - url: /.*
    script: auto
