name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
    branches:
      - main # Тільки для гілки main

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kubernetes tools
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Configure kubectl
        run: |
          echo "${{ secrets.AWS_ACCESS_KEY_ID }}" | base64 --decode > kubeconfig
          export KUBECONFIG=kubeconfig

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/my-deployment my-container=ghcr.io/${{ github.repository }}:latest
          kubectl rollout status deployment/my-deployment

      - name: Monitor deployment
        run: |
          echo "Checking pod status..."
          kubectl get pods -o wide
          echo "Testing if pods are running..."
          kubectl get pods --field-selector=status.phase=Running
